package com.example.androidsqldelightdb.data

import kotlinx.coroutines.flow.Flow
import persondb.PersonEntity

interface PersonDataSource {

    // PersonEntity is the class generated by sql delight
    suspend fun getPersonById(id: Long): PersonEntity?

    // It is not a suspend function as it returns a flow of list of person entity
    // everytime the list is updated.
    fun getAllPersons(): Flow<List<PersonEntity>>

    suspend fun deletePersonById(id: Long)

    suspend fun insertPerson(firstName: String, lastName: String, id: Long? = null)
}